apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog-service-nodeport
  namespace: pensionapp
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
    - name: http
      port: 8025
      targetPort: 8025
      nodePort: 30000
      protocol: TCP
    - name: smtp
      port: 1025
      targetPort: 1025
      nodePort: 30003
      protocol: TCP